### ISSUE TITLE
For what versions?

### ISSUE THREAD

**Issue by Definitelyeson** [t0int1337/BunifuUiCrack#2]
Can you tell for what versions can be use

**Comment by Skeebazac** [comment]
Any versions that under or equal to BunifuLicensing 5.0.0

**Comment by patlgrc** [comment]
i look for the 6.0.1 new licensing .dll, any clue ?

**Comment by t0int1337** [comment]
I can make it for the new version later maybe

**Comment by Overclock303** [comment]
Yes it would be nice. The problem with bunifu is the fact that they sells bugs in their products and you have to paid for the fixes. Also the libs and code are not managed. So.. yes, a 6.0.1 crack would be nice.

**Comment by t0int1337** [comment]
@Overclock303 thanks, i will work on a new crack now.

**Comment by t0int1337** [comment]
@Overclock303 @Skeebazac @patlgrc @Definitelyeson 
Updated for the latest version. (6.0.4)
